name: publish artifactory to the project

on: 
  push: 
    branches: [ main ]
jobs:
  archive-build-down:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1: Create dir
        run: mkdir down
      - name: Step 2: Create file
        run: |
          cd down
          echo hello > hello.html
          cd ..
      - name: Step 3 Upload artifacts
        uses: actions/upload-artifactory@v2
        with:
          name: assets-down
          path: down
